### ISSUE TITLE
要是不能翻墙安装不了TunSafe,因为TunSafe-TAP需要翻墙下载.

### ISSUE THREAD

**Issue by FirePrayer** [liweiDiao/WireGuard#1]
要是不能翻墙安装不了TunSafe,因为TunSafe-TAP需要翻墙下载,楼主能否提供TunSafe-TAP的安装包?

**Comment by liweiDiao** [comment]
在Installer 目录下上传了TunSafe-1.4.exe 文件,  其实这个翻墙工具蛮好用的。但是协议文件只有在翻墙的时候才能加载出来。我现在都是用ssr暂时翻墙后，在用tunsafe连接，ssr是有流量限制的。tunsafe是没有流量限制的。

**Comment by Moke88882001** [comment]
安装时候任然要执行下载，无法链接，安装程序自动放弃了

**Comment by liweiDiao** [comment]
> 安装时候任然要执行下载，无法链接，安装程序自动放弃了

我在chromeExtensions 文件夹下上传了一个chrome 扩展程序，安装后也可以科。学。上网
